# Generated by Django 5.0.3 on 2024-04-10 15:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id_livro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('ano_publicacao', models.PositiveIntegerField(blank=True, null=True)),
                ('ISBN', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resenhas',
            fields=[
                ('id_resenha', models.AutoField(primary_key=True, serialize=False)),
                ('texto_resenha', models.TextField()),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('avaliacao', models.IntegerField()),
                ('ref_livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookly.livros')),
                ('ref_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookly.usuarios')),
            ],
        ),
    ]
